# Generated by Django 6.0.2 on 2026-02-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleexception',
            name='is_working_day',
            field=models.BooleanField(default=False),
        ),
    ]
