# Generated by Django 6.0.2 on 2026-03-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_alter_scheduleexception_is_working_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
