# Generated by Django 6.0.2 on 2026-03-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_scheduleexception_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleexception',
            name='slot_duration',
            field=models.IntegerField(choices=[(15, '15 min'), (30, '30 min')], default=30),
        ),
    ]
