# Generated by Django 6.0.2 on 2026-03-01 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_alter_appointmentslot_doctor_and_more'),
        ('users', '0002_delete_adminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile'),
        ),
        migrations.AlterField(
            model_name='scheduleexception',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.doctorprofile'),
        ),
    ]
