# Generated by Django 6.0.2 on 2026-03-01 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_doctor_alter_appointment_patient'),
        ('scheduling', '0007_alter_appointmentslot_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot_booking',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('doctor', 'slot'), name='unique_doctor_slot'),
        ),
    ]
