# Generated by Django 6.0.2 on 2026-03-01 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_remove_appointment_unique_slot_booking_and_more'),
        ('scheduling', '0007_alter_appointmentslot_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_slot',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'CONFIRMED', 'CHECKED_IN'])), fields=('doctor', 'slot'), name='unique_doctor_slot'),
        ),
    ]
