# Generated by Django 6.0.2 on 2026-03-02 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_remove_appointment_unique_doctor_slot_and_more'),
        ('scheduling', '0007_alter_appointmentslot_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_slot',
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['REQUESTED', 'CONFIRMED', 'CHECKED_IN', 'COMPLETED'])), fields=('doctor', 'slot'), name='unique_doctor_slot'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulelog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedule_logs', to='appointment.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentreschedulelog',
            name='new_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_slot_logs', to='scheduling.appointmentslot'),
        ),
        migrations.AddField(
            model_name='appointmentreschedulelog',
            name='old_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_slot_logs', to='scheduling.appointmentslot'),
        ),
    ]
