apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
data:
  DB_NAME: clinic_db
  DB_USER: postgres
  DB_HOST: db-service
  DB_PORT: "5432"
  # DB_PASSWORD: "password123"
  ALLOWED_HOSTS: "192.168.49.2,localhost,web-service"